-- SQL Schema for Storify Store Database (Supabase PostgreSQL Edition)
-- Copy and run this script inside the Supabase SQL Editor.

-- 1. Create the reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow anyone (public) to view reviews
DROP POLICY IF EXISTS "Enable read access for everyone" ON public.reviews;
CREATE POLICY "Enable read access for everyone"
ON public.reviews
FOR SELECT
TO public
USING (true);

-- 4. Policy: Allow anyone (public) to submit a review
DROP POLICY IF EXISTS "Enable insert access for everyone" ON public.reviews;
CREATE POLICY "Enable insert access for everyone"
ON public.reviews
FOR INSERT
TO public
WITH CHECK (true);

-- NOTE: The 'users' table is handled automatically by Supabase Auth (auth.users)
-- and user metadata (name, phone, address, city, zip) is stored directly in user_metadata.
-- No public.users table is required for this setup.
